package:
    name: mflow
    version: 0.0.7
source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pyzmq

build:
  entry_points:
    - m_dump = mflow.utils.dump:main
    - m_replay = mflow.utils.replay:main
    - m_stats = mflow.utils.stats:main
    - m_split = mflow.utils.split:main
    - m_generate = mflow.utils.generate:main

about:
    home: https://github.com/datastreaming/mflow
    summary: "mflow library."
